data_params:
  batch_size: 2
  num_workers: 16
  augmentation_params:
    resize: 256

train_params:
  name: VNet_test
  model: models_zoo.segmentation.vnet.VNet
  model_params:
    num_filters: 64
    pretrained: False
    num_classes: 3
  loss: losses.CrossEntropyDiceLoss3D
  loss_params: {}
  metrics: [losses.BackgroundDiceScore, losses.BodyDiceScore, losses.TumorDiceScore]
  steps_per_epoch: 1000
  new_save: True
#  weights:
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.01
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 5
    factor: 0.5
    min_lr: 0.000001
  epochs: 300
  augmentation: mix_transform