data_params:
  batch_size: 16
  num_workers: 16
  augmentation_params:
    resize: 512

train_params:
  name: ternausNet
  model: models_zoo.segmentation.unet.TernausNet
  model_params:
    num_filters: 64
    pretrained: False
    num_classes: 3
  loss: losses.CrossEntropyLoss
  loss_params: {}
  metrics: [losses.CrossEntropyLoss]
  steps_per_epoch: 2500
  new_save: True
#  weights:
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 5
    factor: 0.5
    min_lr: 0.000001
  epochs: 300
  augmentation: mix_transform