data_params:
  batch_size: 64
  num_workers: 16
  augmentation_params:
    resize: 256

train_params:
  name: rn34_TverskyLoss
  model: models_zoo.segmentation.resnet.MultiResnet34
  model_params:
    num_filters: 64
    pretrained: True
    num_classes: 3
  loss: losses.TverskyLoss2D
  loss_params: {alpha: 0.6, beta: 0.4}
  metrics: [losses.BackgroundDiceScore, losses.BodyDiceScore, losses.TumorDiceScore]
  steps_per_epoch: 1000
  new_save: True
#  weights:
stages:
-
  load_best: False
  optimizer: Adam
  optimizer_params:
    lr: 0.001
  scheduler: ReduceLROnPlateau
  scheduler_params:
    patience: 5
    factor: 0.5
    min_lr: 0.000001
  epochs: 300
  augmentation: mix_transform