dumps:
  path: ./trained_models   # path to weights dirls
  weights: weights                  # name of weights dir
  logs: logs                        # name of logs dir
  name_save: tt                     # name to save models

data:
  path: ./dataset  # path to data directory
  train_images: images/   # dir to train images
  train_masks: masks/    # dir to labels
  test_images: images_test/  # dir to test
  folds: folds.csv                  # validation folds
  predictions_path: preds.csv       # predictions name
